module Telecine
  class ThreadHandleProxy
    def kill
      raise NotImplementedError, "remote kill not supported"
    end

    def join
      raise NotImplementedError, "remote join not supported"
    end
  end

  class SubjectProxy
    def class
      "[remote]"
    end
  end

  # The reference should:
  #   - be generated by the transport
  #   - contain a mailbox generated by the transport
  #   - use its mailbox to redirect messages to the transport
  #   - disallow certain invalid methods, like remote kill, or remote
  #     thread and class handles
  class Reference
    def initialize(mailbox)
      @mailbox = mailbox
      @thread  = ThreadHandleProxy.new
      @subject = SubjectProxy.new
    end
    attr_reader :mailbox, :thread, :subject
  end
end
